language: ruby
cache: bundler
rvm:
- 3.0.1
before_install: gem install bundler -v 2.2.20
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;'
  - psql -c "CREATE USER david WITH PASSWORD 'password123';"
